/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    DownloadOutlined: typeof import('@ant-design/icons-vue')['DownloadOutlined']
    GithubOutlined: typeof import('@ant-design/icons-vue')['GithubOutlined']
    HomeOutlined: typeof import('@ant-design/icons-vue')['HomeOutlined']
    LockOutlined: typeof import('@ant-design/icons-vue')['LockOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafetyOutlined: typeof import('@ant-design/icons-vue')['SafetyOutlined']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
    WechatOutlined: typeof import('@ant-design/icons-vue')['WechatOutlined']
  }
}
